// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1fHFRgIKDB_J9bCXD2eTs9ghSq0lEha8',
    appId: '1:731897830097:web:13c3bae56384b46c0403f0',
    messagingSenderId: '731897830097',
    projectId: 'unichat-zego',
    authDomain: 'unichat-zego.firebaseapp.com',
    storageBucket: 'unichat-zego.appspot.com',
    measurementId: 'G-Q6VXGRBW7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJUaL8qmwFAnGdNEF_5V_N_gn_nuJIGiE',
    appId: '1:731897830097:android:33dd7294af636f720403f0',
    messagingSenderId: '731897830097',
    projectId: 'unichat-zego',
    storageBucket: 'unichat-zego.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJrAUmj-qPCKr6IaENu4Hwd-HfIi-dCcI',
    appId: '1:731897830097:ios:94189d62b7d9d0ad0403f0',
    messagingSenderId: '731897830097',
    projectId: 'unichat-zego',
    storageBucket: 'unichat-zego.appspot.com',
    iosClientId: '731897830097-6d90ehsedr8kpg0df9dc331rlgc7j0l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
